
# Site settings
title: 王新栋
name: 王新栋
subtitle: 化学博士
email: xdwang_chem@126.com
description: >
  化学博士
baseurl: ""
url: "https://hi-xindong.github.io/"
github_username:  hi-xindong
disqus_baseurl: "https://hi-xindong.github.io/"
disqus_shortname: https-hi-xindong-github-io
permalink: :title
google-site-verification: "EBNpnv4GiHJTmePgRajamxrYtJnc6WlqDyWUITDaSMo"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "王新栋"



